#!/bin/bash

cd $(dirname $0)
. ./common.sh

export PID_FILE=$SRC_ROOT/tmp/apache.pid
export CONFIG=$TMP_DIR/apache.conf

CONFIG_TMPL=$CONF_DIR/apache.conf.devenv
APACHE2=/usr/sbin/apache2


usage() {
	echo "Usage:  $0 <start|stop|restart|status>"
exit 1;
}

is_running() {
	[ ! -f $PID_FILE ] && return 1
	! ps $(cat $PID_FILE 2>/dev/null) >/dev/null && return 1
	return 0
}

status() {
	is_running && echo "Apache is running" || echo "Apache is stopped"
}

start() {
	if is_running ; then
		echo "Apache is already running"
		return 1
	fi

	convert_tmpl $CONFIG_TMPL $CONFIG
	$APACHE2 -f $CONFIG && echo "Apache has been started"
}

stop() {
	if ! is_running ; then
		echo "Apache is already stopped"
		return 1
	fi

	kill $(cat $PID_FILE)

	while is_running ; do
		sleep 0.1
	done
	echo "Apache has been stopped"
}

case "$1" in
	status)
		status
	;;
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	*)
		usage
	;;
esac
