#!/bin/bash

cd $(dirname $0)
. ./common.sh

export PID_FILE=$SRC_ROOT/tmp/hub.pid
START_SCRIPT=$SRC_ROOT/hub/start-dev.sh
REMOTE="escript $SRC_ROOT/scripts/nodetool -sname hub_dev"
HOSTNAME=${hostname}

usage() {
	echo "Usage:  $0 <start|stop|restart|status>"
	exit 1;
}

is_running() {
	$REMOTE ping >/dev/null
	return $?
}

status() {
	is_running && echo "Running" || echo "Stopped"
}

start() {
	$START_SCRIPT "$@"
	echo "hub has been started"
}

stop() {
	$REMOTE stop && echo "hub has been stopped"
}

console() {
	if is_running ; then
		erl -sname 'hub_console' -remsh hub_dev@$HOSTNAME
	else
		start
	fi
}

case "$1" in
	status)
		status
	;;

	start)
		if is_running ; then
			echo "Already running"
			exit 1
		fi
		start -detached
	;;

	stop)
		if ! is_running ; then
			echo "Already stopped"
			exit 1
		fi
		stop
	;;

	console)
		console
	;;

	restart)
		stop
		start -detached
	;;

	*)
		usage
	;;
esac
