#!/bin/bash

cd $(dirname $0)
. ./common.sh

export PID_FILE=$SRC_ROOT/tmp/hub.pid
START_SCRIPT=$SRC_ROOT/hub/start-dev.sh
REMOTE="escript $SRC_ROOT/scripts/nodetool -sname hub_dev"
HOSTNAME=$(hostname)

usage() {
	echo "Usage:  $0 <COMMAND>

Commands:
   start|stop|restart|status   -- control the daemon
   console                     -- start hub in console mode or attach to remote console
"
	exit 1;
}

is_running() {
	$REMOTE ping >/dev/null
}

status() {
	is_running && echo "Hub is running" || echo "Hub is stopped"
}

start() {
	if is_running ; then
		echo "Hab is already running"
		return 1
	fi

	$START_SCRIPT "$@" && echo "Hub has been started"
}

stop() {
	if ! is_running ; then
		echo "Hub is already stopped"
		return 1
	fi

	$REMOTE stop >/dev/null || return 1

	while is_running ; do
		sleep 0.1
	done
	echo "Hub has been stopped"
}

console() {
	if is_running ; then
		erl -remsh hub_dev@$HOSTNAME
	else
		start
	fi
}

case "$1" in
	status)
		status
	;;
	start)
		start -detached
	;;
	stop)
		stop
	;;
	console)
		console
	;;
	restart)
		stop
		start -detached
	;;
	*)
		usage
	;;
esac
