#!/bin/bash

cd $(dirname $0)
. ./common.sh

export PID_FILE=$SRC_ROOT/tmp/hub.pid
START_SCRIPT=$SRC_ROOT/hub/start-dev.sh

usage() {
	echo "Usage:  $0 <start|stop|restart|status>"
	exit 1;
}

is_running() {
	[ ! -f $PID_FILE ] && return 1
	! ps $(cat $PID_FILE) >/dev/null && return 1
	return 0
}

status() {
	is_running && echo "Running" || echo "Stopped"
}

start() {
	$START_SCRIPT "$PID_FILE" -detached
	echo "hub has been started"
}

stop() {
	kill $(cat $PID_FILE)
	echo "hub has been stopped"
}

case "$1" in
	status)
		status
	;;

	start)
		if is_running ; then
			echo "Already running"
			exit 1
		fi
		start
	;;

	stop)
		if ! is_running ; then
			echo "Already stopped"
			exit 1
		fi
		stop
	;;

	restart)
		stop
		start
	;;

	*)
		usage
	;;
esac
