#!/bin/bash

cd $(dirname $0)
. ./common.sh

export PID_FILE=$SRC_ROOT/tmp/nginx.pid
export CONFIG=$TMP_DIR/nginx.conf

CONFIG_TMPL=$CONF_DIR/nginx.conf.devenv
NGINX=/usr/sbin/nginx

usage() {
	echo "Usage:  $0 <start|stop|restart|status>"
exit 1;
}

is_running() {
	[ ! -f $PID_FILE ] && return 1
	! ps $(cat $PID_FILE 2>/dev/null) >/dev/null && return 1
	return 0
}

status() {
	is_running && echo "Nginx is running" || echo "Nginx is stopped"
}

start() {
	if is_running ; then
		echo "Nginx is already running"
		return 1
	fi

	export NGINX_CONF_MODS=$(nginx_conf_modifications)
	convert_tmpl $CONFIG_TMPL $CONFIG
	$NGINX -c $CONFIG && echo "Nginx has been started"
}

stop() {
	if ! is_running ; then
		echo "Nginx is already stopped"
		return 1
	fi

	kill $(cat $PID_FILE)

	while is_running ; do
		sleep 0.1
	done
	echo "Nginx has been stopped"
}

nginx_conf_modifications() {

	echo "
	client_body_temp_path ${TMP_DIR}/nginx-body;
	proxy_temp_path ${TMP_DIR}/nginx-proxy;
	fastcgi_temp_path ${TMP_DIR}/nginx-fastcgi;"

	NGINX_VERSION=$(dpkg-query -W -f='${Version}\n' nginx)
	if dpkg --compare-versions $NGINX_VERSION '>' 1.0.0 ; then
		echo "
	uwsgi_temp_path ${TMP_DIR}/nginx-uwsgi;
	scgi_temp_path ${TMP_DIR}/nginx-scgi;"
	fi
}

case "$1" in
	status)
		status
	;;
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	*)
		usage
	;;
esac
